name: Keep Supabase Active

on:
  schedule:
    # Run once daily at 6 AM UTC (backup to Vercel cron at 12 PM UTC)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Keep-Alive Endpoint
        run: |
          curl -f https://computer-science-society-usls.vercel.app/api/keep-alive || exit 1
        continue-on-error: true
        
      - name: Log Success
        if: success()
        run: echo "Keep-alive ping successful at $(date)"
        
      - name: Log Failure
        if: failure()
        run: echo "Keep-alive ping failed at $(date)"
